files:
  - source: dist/self-service-reasons/1.0.7/cancellation-reasons_en.json
    translation: dist/self-service-reasons/1.0.7/cancellation-reasons_%two_letters_code%.json
  - source: dist/self-service-reasons/1.0.7/replacement-reasons_en.json
    translation: dist/self-service-reasons/1.0.7/replacement-reasons_%two_letters_code%.json