files:
  - source: dist/self-service-reasons/1.10.2/cancellation-reasons_en.json
    translation: /dist/self-service-reasons/1.10.2/cancellation-reasons_%two_letters_code%.json
  - source: dist/self-service-reasons/1.10.2/replacement-reasons_en.json
    translation: /dist/self-service-reasons/1.10.2/replacement-reasons_%two_letters_code%.json